CREATE TABLE GroupComments( 
	groupCommentID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	groupID INTEGER NOT NULL,
	groupPostID INTEGER NOT NULL,
	authorID INTEGER NOT NULL,
	author TEXT NOT NULL,
	content TEXT NOT NULL, 
	creationDate TIMESTAMP,
	FOREIGN KEY(groupPostID)REFERENCES GroupPosts(groupPostID),
	FOREIGN KEY(authorID)REFERENCES users(userID)
	);