CREATE TABLE Followers( 
	fID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	folID INTEGER NOT NULL,
	reqID INTEGER NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY(folID)REFERENCES Users(userID),
	FOREIGN KEY(reqID)REFERENCES User(userID)
);