CREATE TABLE GroupPost( 
	groupPostID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	groupID INTEGER NOT NULL,
	authorID INTEGER NOT NULL,
	author TEXT NOT NULL,
	title TEXT NOT NULL, 
	content TEXT NOT NULL, 
	category TEXT NOT NULL,
	creationDate TIMESTAMP,
	public TEXT,
	FOREIGN KEY(authorID)REFERENCES Users(userID),
	FOREIGN KEY(groupID)REFERENCES GroupChat(groupID)
	);